variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "avail_zone1" {}
variable "avail_zone2" {}
variable "env" {}
variable "myip" {}
variable "ami" {}
variable "instance_type" {}
variable "public_key_pair_path" {}
variable "private_key_pair_path" {}
